### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sharma-shray** [leimao/Console-Snake#7]
![image](https://github.com/leimao/Console-Snake/assets/48922607/ec4b8873-2ef1-418d-9ee9-b4bc31107ef5)
![image](https://github.com/leimao/Console-Snake/assets/48922607/2dcfa69e-8169-452b-b418-21c61994f3b2)

**Comment by leimao** [comment]
@sharma-shray I did not look into the detail of the program. But a quick [solution](https://github.com/leimao/Console-Snake/commit/7ee38117f954238d4ab5859dfbf755acc6adeffc) has been updated and the program should be able to compile with the newer version of CMake.

Please feel free to reopen this issue if it does not work for you.
